-- Seed data is inserted via the application API layer, which handles PII encryption.
-- Use the seed script: pnpm --filter @credit-system/backend seed
--
-- Or create applications via the API:
--   POST /api/v1/applications with a valid JWT token
--
-- Plain-text document IDs cannot be inserted directly into the database
-- because the application layer encrypts them with AES-256-GCM.
